apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app-image
        image: votingappdemo.azurecr.io/app-image:v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: vote-app
spec:
  type: LoadBalancer
  selector:
    app: vote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
